section: screens
	Siloe:
	BluetoothPi:
end

section: aliases
end

section: links
	Siloe:

	BluetoothPi:
end

section: options
	relativeMouseMoves = true
	keystroke(Control+Alt+b) = switchToScreen(BluetoothPi)
	keystroke(Control+Alt+p) = switchToScreen(Siloe)
end
